# Jekyll Settings
markdown: kramdown

# Site settings
version: "0.28"
url: http://google.github.io/truth
title: Truth
tagline: We've made failure a strategy
description: "A proposition/assertion framework for testing in Java"

# Navigation
navigation:
- text: Change
  url: /truth/changelog.html
- text: Javadoc
  url: /truth/api/0.28/
- text: FAQ
  url: /truth/faq.html
- text: Usage
  url: /truth/usage.html
- text: Home
  url: /truth
