# Jekyll Settings
markdown: kramdown

# Site settings
version: "0.28"
url: http://google.github.io/truth
title: Truth
tagline: We've made failure a strategy
description: "A proposition/assertion framework for testing in Java"

# Navigation
navigation:
- text: Compare
  url: /truth/comparison
- text: Javadoc
  url: /truth/api/0.28/
- text: FAQ
  url: /truth/faq
- text: Benefit
  url: /truth/benefits
- text: Home
  url: /truth
